name: Cypress Tests

on:
  push:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 🔥 Override corporate registry
      - name: Use public npm registry
        run: npm config set registry https://registry.npmjs.org/

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run Cypress
      - name: Run Cypress tests
        run: npx cypress run

      # Generate report
      - name: Generate report
        run: npm run cypress:report

      # Upload report
      - name: Upload Cypress Report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/html
